### ISSUE TITLE
Investigate UI lag after replay

### ISSUE THREAD

**Issue by micheljung** [micheljung/downlords-faf-client#199]
Androish reported a UI lag at the end of a replay

**Comment by Androish** [comment]
Hey.

To clarify. This has to do with live replay. it happens when you are at close to realtime as you allowed to be, and the game you are observing ends. the replay will slow down/freeze for a little(sometimes forever) then usually go on at your max simspeed(or whatever setting you have it at) from there on. I think it must be something with the live replay server not the client?

**Comment by micheljung** [comment]
Thanks for the clarification. I don't know the replay server internals, but there's a good chance it's not very efficient :-)

**Comment by yenon** [comment]
All players have to leave the game for the live replay to unfreeze, atleast thats what i managed to find out, downlords client most likely isn't the problem here, its probably the server.

**Comment by micheljung** [comment]
Thanks for investigating, I'm closing this then :-)
